# Generated by Django 4.0.3 on 2022-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0002_alter_cargo_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
