# Generated by Django 4.0.3 on 2022-03-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0003_empleado_sueldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
