# Generated by Django 4.0.3 on 2022-03-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0007_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
