# Generated by Django 4.0.3 on 2022-03-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0011_alter_empleado_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
