# Generated by Django 4.0.3 on 2022-03-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0012_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['id'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
